### ISSUE TITLE
Paynow button is not working

### ISSUE THREAD

**Issue by patelmayank** [payu-intrepos/PayUMoney-IOS-SDK#14]
Please fine the attachment i am not able to click on the pay now button why ?  i am using credit/Debit card part 

![screen shot 2017-07-08 at 1 51 43 pm](https://user-images.githubusercontent.com/8298590/27983856-d716f810-63e4-11e7-8bbd-3a6144116604.png)

**Comment by AbhishekGCopper** [comment]
Facing the same issue, the button just won't enable
