### ISSUE TITLE
is that possible to change its appearance ?

### ISSUE THREAD

**Issue by Midhunkmohan** [payu-intrepos/PayUMoney-IOS-SDK#15]
I have read PayUMoney's docs and integrated the iOS SDK . I just want to know, is that possible to change its appearance ? . i haven't got any other tutorials for customizing. if any one knows please help me . thanks in advance

**Comment by DishaMukherjee** [comment]
Hi,

Below is the link for downloading the required integration kit: 
https://github.com/payu-intrepos/PayUMoney-IOS-SDK/tree/master/PlugNPlay/Objective-C%20SampleApp. Hope this will help you.
