### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber compare:]: nil argument'

### ISSUE THREAD

**Issue by RajSwiftIos** [payu-intrepos/PayUMoney-IOS-SDK#17]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber compare:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ebd8f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001139f2deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ebd8e9d +[NSException raise:format:] + 205
	3   CoreFoundation                      0x000000010eae9e91 -[__NSCFNumber compare:] + 81
	4   PayUMoneyCoreSDK                    0x000000011386283a +[PUMUtils validateAmount:] + 404
	5   PayUMoneyCoreSDK                    0x000000011385644a +[PayUMoneyCoreSDK initWithTxnParam:error:] + 466
	6   PlugNPlay                           0x000000011394d590 +[PlugNPlay presentPaymentViewControllerWithParams:onViewController:WithCompletionBlock:] + 237
	7   PlugNPlay                           0x000000011394d410 +[PlugNPlay presentPaymentViewControllerWithTxnParams:onViewController:withCompletionBlock:] + 147
	8   HeadsUp7                            0x000000010d2237e7 __44-[AppDelegate openPayUMoney:withController:]_block_invoke + 231
	9   HeadsUp7                            0x000000010d1e724d __60+[SAHelperClass generateHashFromServer:withCompletionBlock:]_block_invoke + 285
	10  HeadsUp7                            0x000000010d2163ac __59+[PUSAWSManager getWebServiceResponse:withCompletionBlock:]_block_invoke + 300
	11  CFNetwork                           0x0000000111cf7a25 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	12  CFNetwork                           0x0000000111d0a35e __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 302
	13  Foundation                          0x0000000112423873 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	14  Foundation                          0x000000011235f5d5 -[NSBlockOperation main] + 101
	15  Foundation                          0x0000000112342556 -[__NSOperationInternal _start:] + 646
	16  Foundation                          0x0000000112342167 __NSOQSchedule_f + 194
	17  libdispatch.dylib                   0x0000000114b1749b _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x0000000114afd988 _dispatch_queue_drain + 2215
	19  libdispatch.dylib                   0x0000000114afcea9 _dispatch_queue_invoke + 601
	20  libdispatch.dylib                   0x0000000114affaf2 _dispatch_root_queue_drain + 1420
	21  libdispatch.dylib                   0x0000000114aff561 _dispatch_worker_thread3 + 111
	22  libsystem_pthread.dylib             0x0000000114e485a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x0000000114e4807d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by DishaMukherjee** [comment]
If you are using latest PnP module then also use latest dependencies. 

Kindly go through link https://github.com/citruspay/citruspay-ios-sdk/releases/tag/graphics.2.1.0 or git clone in a recursive manner.
