### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 3.2.3

### ISSUE THREAD

**Issue by mayurpatel1845** [payu-intrepos/PayUMoney-IOS-SDK#20]
Module compiled with Swift 4.0 cannot be imported in Swift 3.2.3: /Pods/PayUmoney_PnP/PlugNPlay/PlugNPlay.framework/Mo

**Comment by dev-vinoth** [comment]
1+

**Comment by SalmanGhumsani** [comment]
is there any update?

**Comment by mayurpatel1845** [comment]
No mat i hvn't any solution for this. :(

**Comment by DishaMukherjee** [comment]
Hi All,

We have updated our iOS SDK. Now our kit is in objective C which is compatible with Swift. You can integrate it with help of bridging header.

You can download kit from below link:
https://github.com/payu-intrepos/PayUMoney-IOS-SDK
