### ISSUE TITLE
IP address with Port number in Surl Params not accepting

### ISSUE THREAD

**Issue by iSolutionsApps** [payu-intrepos/PayUMoney-IOS-SDK#22]
I have tried with IP address with Port number for Success Url like 
## http://xxx.xxx.xx.x:8090/v1/paymentSuccess

But it returns "Surl is invalid" message. Please help me to solve this issue

**Comment by DishaMukherjee** [comment]
Kindly pass absolute Success URL and Failure URL as IP address will not work.
