### ISSUE TITLE
Need to change Continue Shopping button title

### ISSUE THREAD

**Issue by V1992** [payu-intrepos/PayUMoney-IOS-SDK#23]
I am using iOS PnP SDK. 
Test account credentials are used to test the payment.
Once the payment got success I got the below screenshot having a Continue Shopping button
![simulator screen shot - iphone 6 plus - 2018-03-12 at 18 00 22](https://user-images.githubusercontent.com/12439866/37325228-f662abec-26b2-11e8-8476-c94414fbd961.png)
 
This button gets redirect to the viewcontroller page where the payment started while taps.
So I want to change the  Continue Shopping button title now. 
**How can I change this?**

I have customized the color also. 
![simulator screen shot - iphone 6 plus - 2018-03-13 at 11 59 48](https://user-images.githubusercontent.com/12439866/37326049-56e59aa8-26b6-11e8-8dfc-40bad24811ec.png)

But when I tap on paynow button again I got the below screen with its on default color.

![simulator screen shot - iphone 6 plus - 2018-03-12 at 18 00 22](https://user-images.githubusercontent.com/12439866/37325228-f662abec-26b2-11e8-8476-c94414fbd961.png)

**Comment by DishaMukherjee** [comment]
We don't have the support for customizing that text You can replace the success screen with your own screen. More info here - https://www.payumoney.com/dev-guide/mobilecheckout/ios.html#response-handling
