### ISSUE TITLE
Need to change Payumoney logo color

### ISSUE THREAD

**Issue by V1992** [payu-intrepos/PayUMoney-IOS-SDK#24]
I am using iOS PnP SDK.

![simulator screen shot - iphone 6 plus - 2018-03-13 at 11 32 41](https://user-images.githubusercontent.com/12439866/37325800-5e877d72-26b5-11e8-952d-300bf4301454.png)

I want to change the payumoney logo color in the screenshot while loading.
Please help

**Comment by DishaMukherjee** [comment]
Hi 

You cannot change the payumoney logo color.
