### ISSUE TITLE
On payment success page.. its showing No Internet connection warning

### ISSUE THREAD

**Issue by sijukarunakaran** [payu-intrepos/PayUMoney-IOS-SDK#26]
![simulator screen shot - iphone x - 2018-03-20 at 16 50 43](https://user-images.githubusercontent.com/2913775/37653860-4b7acd2c-2c66-11e8-9c3f-761338517a48.png)

All payment process working fine but no internet warning showing at the payment success page.

**Comment by DishaMukherjee** [comment]
Error attached in the screenshot is not possible. Kindly use below link for downloading the required integration kit: 
https://github.com/payu-intrepos/PayUMoney-IOS-SDK/tree/master/PlugNPlay/Objective-C%20SampleApp 

Below is the test card details for doing a test transaction in the testing mode. 
Card No - 5123456789012346 
Expiry - 05/2020 
CVV - 123 
Name - Test
