### ISSUE TITLE
 this results in an NSURL instance with an empty URL string payumoney

### ISSUE THREAD

**Issue by gaus55** [payu-intrepos/PayUMoney-IOS-SDK#29]
Integration[10208:326633] -[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.

**Comment by sforsethi** [comment]
> Integration[10208:326633] -[NSURL init] called; this results in an NSURL instance with an empty URL string. Please use one of the documented NSURL initialization methods instead (initWithString:, initFileURLWithPath:, etc.). This message shown only once.

Hey I'm facing the same issue, did you find a way around it ?

**Comment by DishaMukherjee** [comment]
Can raise ticket at help.payu.in with screen recording and error logs. Also, kindly provide below details:
1. XCode Version 
2. SDK version
3. Device and its version in which you are facing issue 
4. Param posting to PayU.
