### ISSUE TITLE
App crash while press back button before load merchant details ? (Swift 4.0)

### ISSUE THREAD

**Issue by riteshpatel0** [payu-intrepos/PayUMoney-IOS-SDK#30]
Hello PayUTeam,

I have facing one issue in  Swift 4.0 Project.
After present payumoney screen through this method **PlugNPlay.presentPaymentViewController**  merchant details is not loaded in screen and user press back button at that time alert is coming and press yes on that alert screen. PayUMoney screen dismiss successfully but then after received  EXC_BAD_ACCESS error. 
```
PlugNPlay.setDisableWallet(false);

PlugNPlay.presentPaymentViewController(withTxnParams: objPayU, on: self?.navigationController){ (dict, error, response) in
                    
                    print("PayUMoney Response : \(String(describing: response))")
                    print("PayUMoney Data : \(String(describing: dict) )")
                    
                    if(error != nil){
                        print("ERROR PayUMoney : \(String(describing: error?.localizedDescription))")
                    }else{
                       
                       if let dictObj = dict!["result"] as? NSDictionary{

                      }
                      
                    }
                }
```

Let me know  any solution from your side...

**Comment by RajvinderPayU** [comment]
Hi Ritesh,

We are not able to reproduce this error at our end, can you send a sample app in which you are facing this issue?

**Comment by nagarajaghantasala** [comment]
Hi @RajvinderPayU ,

I am also facing same issue. 

You can check the below scenario.
if you tap on **Back** button immediate after **PlugNPlay.presentPaymentViewController** presented will show popup **"Are you sure want to cancel the transaction?"**, then if you proceed with **YES**, you can see the App crash.

**Comment by DishaMukherjee** [comment]
Hi Nagaraja

We are not able to reproduce this error at our end, can you send a sample app in which you are facing this issue?

**Comment by Techunido** [comment]
step 1. click on paytm option 
step 2. click on main back button on top not paytm back button. 

having "Application tried to present modally an active controller"

**Comment by naveen488** [comment]
Hi @nagarajaghantasala, 

Have you found any solutions for the above crash issues, am also facing the same issue in my iOS App .
