### ISSUE TITLE
iOS App is Crashing when moving back immediately from PayUmoney landing page. 

### ISSUE THREAD

**Issue by Ravikumawat1990** [payu-intrepos/PayUMoney-IOS-SDK#34]
Hello,
I am facing an issue while integrating PayUmoney in iOS application :
 Issue
1. Being on PayUmoney screen if we press back button the dialogue get appear & when the yes option is tapped, the application gets crashed. It is a fast process in which the data doesn't get loads in the background, the application get crashed meanwhile the loader appears on the previous screen. 
 2. Response is coming slow due to which loader is not visible on payUmoney screen in ios application.

Url used  :-  https://developer.payumoney.com/ios/#prerequisites
Type used :-  pod 'PayUmoney_PnP'

**Comment by Ravikumawat1990** [comment]
I Attached a video in zip please see this video 

[VID_20180709_185039913.zip](https://github.com/payu-intrepos/PayUMoney-IOS-SDK/files/2176334/VID_20180709_185039913.zip)

**Comment by DishaMukherjee** [comment]
Hi Ravi,

Kindly confirm which iOS version you are using. And also tell which iOS devices you are testing with.

**Comment by Ravikumawat1990** [comment]
iOS version is 11.3
 An issue in appearing in all ios device.

**Comment by DishaMukherjee** [comment]
Are you able to reproduce it on our sample app

**Comment by Ravikumawat1990** [comment]
No, it is getting produced in our developed demo instructed by your sample app.
