### ISSUE TITLE
Latest pod version Payment Mode via NB,CC, DC not working

### ISSUE THREAD

**Issue by mohsinalimat** [payu-intrepos/PayUMoney-IOS-SDK#35]
Hello,

Payment Mode in:
Netbanking (NB)
Debit Card(DC)
Credit Card(CC)

With latest version in your pod below lines are not working.. Why?

 [PlugNPlay setDisableCards:NO];
 [PlugNPlay setDisableNetbanking:NO];
 [PlugNPlay setDisableWallet:YES];

**Comment by mohsinalimat** [comment]
?

**Comment by RajvinderPayU** [comment]
These methods are now removed from the SDK, now Payment modes can be enabled/disabled from the PayUMoney dashboard (login with your account credentials) on the go without doing any change in the app.

**Comment by DishaMukherjee** [comment]
If you want to disable wallet, kindly drop the mail to merchantcare@payumoney.com

**Comment by mohsinalimat** [comment]
But want to show only Payment Mode in:
Netbanking (NB)
Debit Card(DC)
Credit Card(CC)
