### ISSUE TITLE
paymet_realted_details_for_mobile_sdk hash is invalid..

### ISSUE THREAD

**Issue by deepkumar18** [payu-intrepos/PayUMoney-IOS-SDK#40]
Hi ,
 I integrated your kit in my application .. With the test key's from back end they genearted the hash key.. this key working properly in android but when come to ios it is showing paymet_realted_details_for_mobile_sdk hash is invalid... can you please help me in this?

**Comment by DishaMukherjee** [comment]
Hello Deep, 

Thank you for contacting us.
Please make sure you have generated payment_hash with 
sha512(key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5||||||salt)
Use 11 empty pipes between email and salt if you are not using any udf. 

Please have a look at our server-side document to generate hashes at your server:
**https://github.com/payu-intrepos/Documentations/wiki/4.-Server-Side**
You can use our online tool to validate your hashes from below link: **http://payuhashgeneration.herokuapp.com/**

**Comment by deepkumar18** [comment]
Hi @DishaMukherjee  thank for your reply.. Our server side also they are generating as u mentioned i have a doubt how it is working for android sdk not for ios?

**Comment by deepkumar18** [comment]
We are using as like ur sample project but no luck...[](url)

**Comment by sharathfantain** [comment]
@deepkumar18 Facing the same issue here, its working on android and not on iOS. Kindly reply in case you have found the solution.

**Comment by DishaMukherjee** [comment]
Hi Deepak and Sharath,

It seems like you both are using the wrong kit of PayUMoney.

Please download the required integration kit from https://github.com/payu-intrepos/PayUMoney-IOS-SDK.

**Comment by sharathfantain** [comment]
@DishaMukherjee 

We have actually integrated the SDK using pods as per your developer guide. i.e, we added the below line in our podfile and installed the pod.

pod 'PayUmoney_PnP'

I am guessing your pod must be pointing to the right kit. So let me know if the pod is not the way to integrate your sdk.

**Comment by nagarajuc** [comment]
Hi, success URL fails when it has ? and :(for adding port to URI). Should we encode success URL with any encoding scheme .?

**Comment by DishaMukherjee** [comment]
Kindly integrate with updated SDK with SURL/FURL validation. Use below link to integrate:
https://github.com/payu-intrepos/PayUMoney-IOS-SDK
