### ISSUE TITLE
PayU Crashing on payment.. 

### ISSUE THREAD

**Issue by thejogsa** [payu-intrepos/PayUMoney-IOS-SDK#43]
Same crash occuring in my LIVE Application. 

I tried it in demo application , its crashing while payment proceed. Same thing happen in my application.

2019-03-26 16:07:22.994102+0530 PlugNPlayFrameworkExample[16185:177309] Hash output --------- <9288bd23 17fe19d5 85440e04 ce819d1e f5716915 5e4df96f 71fc41b0 50371a97 8d1278c6 e29c295f 60702637 caef55f7 1b4c00fd a1453f54 f8f639bb 59f513c4>
2019-03-26 16:07:23.427141+0530 PlugNPlayFrameworkExample[16185:177309] NSScanner: nil string argument
2019-03-26 16:07:24.262108+0530 PlugNPlayFrameworkExample[16185:177309] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b3751bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010a913735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b2c14ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010b3e4541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010b370c4b __createDictionary + 43
	5   CoreFoundation                      0x000000010b370bff +[NSDictionary dictionaryWithObject:forKey:] + 47
	6   PlugNPlay                           0x000000010a0c2630 -[PUMFetchUserDataAPI getSCAndWalletDetails] + 69
	7   PlugNPlay                           0x000000010a0cb2bf __46-[PnPWalletPayViewController fetchUserDataAPI]_block_invoke + 193
	8   PayUMoneyCoreSDK                    0x000000010a1a8cbb __56-[PayUMoneyCoreSDK fetchUserDataAPIWithCompletionBlock:]_block_invoke + 308
	9   PayUMoneyCoreSDK                    0x000000010a1952cb __136-[PUMRequestManager hitWebServiceForURLWithPostBlock:isAccessTokenRequired:webServiceURL:urlCategory:withBody:andTag:completionHandler:]_block_invoke_2 + 159
	10  libdispatch.dylib                   0x000000010e290595 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x000000010e291602 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x000000010e29e99a _dispatch_main_queue_callback_4CF + 1541
	13  CoreFoundation                      0x000000010b2da3e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	14  CoreFoundation                      0x000000010b2d4a76 __CFRunLoopRun + 2342
	15  CoreFoundation                      0x000000010b2d3e11 CFRunLoopRunSpecific + 625
	16  GraphicsServices                    0x0000000112d991dd GSEventRunModal + 62
	17  UIKitCore                           0x0000000110cec81d UIApplicationMain + 140
	18  PlugNPlayFrameworkExample           0x0000000109dbf2a0 main + 112
	19  libdyld.dylib                       0x000000010e307575 start + 1
	20  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

![Screenshot 2019-03-26 at 4 11 36 PM](https://user-images.githubusercontent.com/8350797/54990934-e03f6e00-4fe1-11e9-96ca-f78c3ea17128.png)

**Comment by DishaMukherjee** [comment]
Hi,

Kindly drop us a mail at techsupport@payumoney.com with following details:

Merchant id
Problem Statement ( be more elaborative)
Time/Date since
SPOC/Developer's contact name & number 
Screenshot and/or logs or transaction Id of the problem (if possible)

**Comment by dathu7728** [comment]
Now its give the Failuer Response

Hash output --------- <aae3025b cdff9a3c 48583225 1c3a4c7f 1148a80d 867500a5 1ded1709 1a1a05d0 61e77de9 a7dcedd1 59d1bd43 3f05f08f b2ab8521 8e8b307d 2c771215 827c9c61>
2019-03-26 17:22:04.481573+0530 BASIYN[302:19711] NSScanner: nil string argument
2019-03-26 17:22:46.025707+0530 BASIYN[302:19711]  Failuer Response--->>>   (null)
2019-03-26 17:22:50.069391+0530 BASIYN[302:19711]  Failuer Error--->>>   Error Domain=com.payumoney.ErrorDomain Code=7025 "Some error occured!
Please try again." UserInfo={NSLocalizedDescription=Some error occured!
Please try again.}
Error Domain=com.payumoney.ErrorDomain Code=7025 "Some error occured!
Please try again." UserInfo={NSLocalizedDescription=Some error occured!
Please try again.}

**Comment by thejogsa** [comment]
> Hi,
> 
> Kindly drop us a mail at [techsupport@payumoney.com](mailto:techsupport@payumoney.com) with following details:
> 
> Merchant id
> Problem Statement ( be more elaborative)
> Time/Date since
> SPOC/Developer's contact name & number 
> Screenshot and/or logs or transaction Id of the problem (if possible)

**Comment by thejogsa** [comment]
> Hi,
> 
> Kindly drop us a mail at [techsupport@payumoney.com](mailto:techsupport@payumoney.com) with following details:
> 
> Merchant id
> Problem Statement ( be more elaborative)
> Time/Date since
> SPOC/Developer's contact name & number 
> Screenshot and/or logs or transaction Id of the problem (if possible)

Hi.. DishaMukherjee 
Please run your sample application. Also getting same in this. 

Thanks 
Jogendra Singh

**Comment by dathu7728** [comment]
> > Hi,
> > Kindly drop us a mail at [techsupport@payumoney.com](mailto:techsupport@payumoney.com) with following details:
> > Merchant id
> > Problem Statement ( be more elaborative)
> > Time/Date since
> > SPOC/Developer's contact name & number 
> > Screenshot and/or logs or transaction Id of the problem (if possible)
> 
> Hi.. DishaMukherjee
> Please run your sample application. Also getting same in this.
> 
> Thanks
> Jogendra Singh

yes
