### ISSUE TITLE
PayU SDK Crashing .. Same Crash in Sample Application. Please have a look this.

### ISSUE THREAD

**Issue by thejogsa** [payu-intrepos/PayUMoney-IOS-SDK#45]
ame crash occuring in my LIVE Application.

I tried it in demo application , its crashing while payment proceed. Same thing happen in my application.

2019-03-26 16:07:22.994102+0530 PlugNPlayFrameworkExample[16185:177309] Hash output --------- <9288bd23 17fe19d5 85440e04 ce819d1e f5716915 5e4df96f 71fc41b0 50371a97 8d1278c6 e29c295f 60702637 caef55f7 1b4c00fd a1453f54 f8f639bb 59f513c4>
2019-03-26 16:07:23.427141+0530 PlugNPlayFrameworkExample[16185:177309] NSScanner: nil string argument
2019-03-26 16:07:24.262108+0530 PlugNPlayFrameworkExample[16185:177309] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
0 CoreFoundation 0x000000010b3751bb __exceptionPreprocess + 331
1 libobjc.A.dylib 0x000000010a913735 objc_exception_throw + 48
2 CoreFoundation 0x000000010b2c14ec _CFThrowFormattedException + 194
3 CoreFoundation 0x000000010b3e4541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
4 CoreFoundation 0x000000010b370c4b __createDictionary + 43
5 CoreFoundation 0x000000010b370bff +[NSDictionary dictionaryWithObject:forKey:] + 47
6 PlugNPlay 0x000000010a0c2630 -[PUMFetchUserDataAPI getSCAndWalletDetails] + 69
7 PlugNPlay 0x000000010a0cb2bf __46-[PnPWalletPayViewController fetchUserDataAPI]_block_invoke + 193
8 PayUMoneyCoreSDK 0x000000010a1a8cbb __56-[PayUMoneyCoreSDK fetchUserDataAPIWithCompletionBlock:]_block_invoke + 308
9 PayUMoneyCoreSDK 0x000000010a1952cb __136-[PUMRequestManager hitWebServiceForURLWithPostBlock:isAccessTokenRequired:webServiceURL:urlCategory:withBody:andTag:completionHandler:]_block_invoke_2 + 159
10 libdispatch.dylib 0x000000010e290595 _dispatch_call_block_and_release + 12
11 libdispatch.dylib 0x000000010e291602 _dispatch_client_callout + 8
12 libdispatch.dylib 0x000000010e29e99a _dispatch_main_queue_callback_4CF + 1541
13 CoreFoundation 0x000000010b2da3e9 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9
14 CoreFoundation 0x000000010b2d4a76 __CFRunLoopRun + 2342
15 CoreFoundation 0x000000010b2d3e11 CFRunLoopRunSpecific + 625
16 GraphicsServices 0x0000000112d991dd GSEventRunModal + 62
17 UIKitCore 0x0000000110cec81d UIApplicationMain + 140
18 PlugNPlayFrameworkExample 0x0000000109dbf2a0 main + 112
19 libdyld.dylib 0x000000010e307575 start + 1
20 ??? 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dathu7728** [comment]
@thejogsa Any solution ?

**Comment by RajvinderPayU** [comment]
@dathu7728 & @thejogsa we are working on it, meanwhile could you please send your MIDs (merchant ID) on  techsupport@payumoney.com. We will be able to solve this issue faster on your production app.

**Comment by dathu7728** [comment]
> @dathu7728 & @thejogsa we are working on it, meanwhile could you please send your MIDs (merchant ID) on [techsupport@payumoney.com](mailto:techsupport@payumoney.com). We will be able to solve this issue faster on your production app.

@RajvinderPayU  already sent to techsupport@payumoney.com

**Comment by RajvinderPayU** [comment]
could you please check if it is solved on your production app or not?

**Comment by dathu7728** [comment]
> could you please check if it is solved on your production app or not?

no its not working, i getting same issue

 Hash output --------- <be38856e 05c83f6d 69b01a20 7467428d 4c0d97f4 dbeee610 95aab778 d87f647f 854ae5d3 10511703 72a7d78e e6dcc4d5 8d70e376 f87a7181 8cb8ebc0 5644e1fa>
2019-03-27 11:29:19.580527+0530 BASIYN[487:97431] NSScanner: nil string argument
2019-03-27 11:29:20.797267+0530 BASIYN[487:97431] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x19c1bdea4 0x19b38da50 0x19c135384 0x19c0bb870 0x19c1bd580 0x19c0c0118 0x104764398 0x10476c698 0x10443d4e4 0x104429d90 0x105813824 0x105814dc8 0x105822a78 0x19c14dce4 0x19c148bac 0x19c1480e0 0x19e3c1584 0x1c935cc00 0x10286f914 0x19bc06bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by DishaMukherjee** [comment]
Kindly share the ticket id which you have raised to techsupport@payumoney.com.

**Comment by dathu7728** [comment]
> Kindly share the ticket id which you have raised to [techsupport@payumoney.com](mailto:techsupport@payumoney.com).

The ticket number for your submitted query is 04714170.

**Comment by dathu7728** [comment]
now its working, Thank you @RajvinderPayU

**Comment by hussainashraf4u** [comment]
The issue still exist, it seems like there is something to do with the account activation, please confirm.

Thanks
