### ISSUE TITLE
surl and furl incorrect error in iOS SDK (working fine in Android)

### ISSUE THREAD

**Issue by vinaykrgupta** [payu-intrepos/PayUMoney-IOS-SDK#47]
I am using surl like http://mybackned.org:5000/api/v1/Payment/callback?orderId=3e583e2b6ad24c7 
but it's not working if I use -, : or ? across url. 
Same URL is working fine in Android.

**Comment by DishaMukherjee** [comment]
We have checked your above URL both in Andriod and iOS but no response is getting fetched. We recommend you to use POST call acceptable URL. Don't append anything in SURL/FURL.

**Comment by vinaykrgupta** [comment]
The hostname is not actual URL. As I already mentioned that It's working fine for Android. 
In iOS, It's giving surl is invalid without redirecting to PayuMoney Page.
If I remove : and ? from url, it redirect to PayUmoney page. 
Special characters like :, ? and - are not working. Why so ?
can you tell me which type of encoding I should use to make special characters encrypted.
