### ISSUE TITLE
Prevent interactive dismissal of Payment View Controller(PlugNPlay SDK) in iOS 13 and above

### ISSUE THREAD

**Issue by mahendragp** [payu-intrepos/PayUMoney-IOS-SDK#50]
I'm collecting payment from customer using Pay-U-Money in following way...

    PlugNPlay.presentPaymentViewController(withTxnParams: txnParam, on: parentVC) { (response, error, extraParam) in
        //code goes here
    }
**PlugNPlay** _is sub class of_ **NSObject**

>Cocoa Pod used:
> pod 'PayUmoney_PnP'

So when I present the payment view controller, user can dismiss view controller by dragging down the view controller.

It is by default enabled for every presented view controller > iOS 13 versions

So how can I disable integrative dismissal of view controller?

Yes, I know that I can set modalPresentationStyle property over view controller but in PayUmoney SDK I did't found any UIViewController's sub class.

**Comment by RajvinderPayU** [comment]
Please use the latest version. Let us know if you are still facing the issue.

**Comment by mahendragp** [comment]
I'm using cocoa pods and I've uninstalled and then install new pod 'PayUmoney_PnP' but still user is able to dismiss the payment view controller interactively by dragging dow the view controller.

**Comment by RajvinderPayU** [comment]
Which version of ** PayUmoney_PnP** are you using?

**Comment by mahendragp** [comment]
The following PayUmoney_PnP pod version is used in my application.

 PayUmoney_PnP (2.5.0)

**Comment by RajvinderPayU** [comment]
Please use the Latest version 2.5.1.

**Comment by mahendragp** [comment]
Thank you. Now its working.
