### ISSUE TITLE
unable to hide details option in payment screen  

### ISSUE THREAD

**Issue by sombizbuzzz** [payu-intrepos/PayUMoney-IOS-SDK#52]
hi i am using Plug N Play UI , in payment screen i dont want details option . not able to see any property which can make remove this UI 

 
![Simulator Screen Shot - iPhone 7 - 2019-12-21 at 11 26 21](https://user-images.githubusercontent.com/43329978/71303928-3a405900-23e5-11ea-9bff-ca30641892e6.png) its coming like this 

i dont want that UI part 

<img width="434" alt="Screen Shot 2019-12-21 at 11 32 11 AM" src="https://user-images.githubusercontent.com/43329978/71303963-acb13900-23e5-11ea-98b6-112f6f5962bf.png">

**Comment by RajvinderPayU** [comment]
There is no option to remove this.
