### ISSUE TITLE
PayUMoney SDK not working on sandbox env. On Live env. Working fine.

### ISSUE THREAD

**Issue by twcjogendra** [payu-intrepos/PayUMoney-IOS-SDK#53]
When I click on payment, It will ask for card details after that it will show only this screen. 
No other response. 
 
![PayU](https://user-images.githubusercontent.com/59724693/72134850-07b5ca80-33ab-11ea-9b19-2f6ff7efebfa.png)

Please suggest how to resolve this.

**Comment by DishaMukherjee** [comment]
Sandbox issue has been fixed, you can check now. 

Below is the test card details for doing a test transaction in the testing mode. 
Card Name: Test 
Card No - 5123456789012346 
Expiry - 05/2020 
CVV - 123 
Kindly enter ‘123456’ as OTP on bank page simulator.
