### ISSUE TITLE
App will crash

### ISSUE THREAD

**Issue by selva-ios** [payu-intrepos/PayUMoney-IOS-SDK#56]
App will crash when i click back button before payment method load.
Xcode : Version 11.3.1 (11C504)
iOS : 13,12.4.2
Swift 5.0

Terminating app due to uncaught exception 'NSDecimalNumberOverflowException', reason: 'NSDecimalNumber overflow exception'
*** First throw call stack:
(0x1cf3fe190 0x1ce5d39f8 0x1cf3083b0 0x1cfea5084 0x1cfea4300 0x1cfea42a4 0x1023f88b4 0x1023f0854 0x1023f563c 0x1029476f4 0x102948c78 0x1029566fc 0x1cf38fb30 0x1cf38aa68 0x1cf389fc4 0x1d158b79c 0x1fbd12c38 0x100d469c4 0x1cee4a8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by DishaMukherjee** [comment]
Selva,

Kindly share screen-recording of error with params posting to PayU at https://help.payu.in/.

**Comment by DishaMukherjee** [comment]
Selva,

Kindly share screen-recording of error with params posting to PayU at https://help.payu.in/.

**Comment by SelvaMacApp** [comment]
there is no option for uploading video and params

**Comment by SelvaMacApp** [comment]
Can I share here?

**Comment by DishaMukherjee** [comment]
Yes, you can share it here. Also in the above link, there is an option available for uploading the file.

**Comment by DishaMukherjee** [comment]
Make sure you do not share salt here.

**Comment by SelvaMacApp** [comment]
ok

**Comment by SelvaMacApp** [comment]
Params posting to PayU


phone: 96******96
email: ******@gmail.com
amount: 799.00
environment: PUMEnvironment
firstname: Ignasious Jegan
key: icwIL6Rw
merchantid: 6934189
surl: https://www.payumoney.com/mobileapp/payumoney/success.php
furl: https://www.payumoney.com/mobileapp/payumoney/failure.php
productInfo: BATHROOM DEEP CLEANING
udf1:  
udf2:  
udf3:  
udf4:  
udf5:  
udf6:  
udf7:  
udf8:  
udf9:  
udf10:

**Comment by SelvaMacApp** [comment]
The link have only following options
<img width="461" alt="Screenshot 2020-02-28 at 12 51 51 PM" src="https://user-images.githubusercontent.com/37236348/75519478-58e84f00-5a29-11ea-88dd-5f0e12e124a5.png">

**Comment by DishaMukherjee** [comment]
Kindly click on setup ur Payu Account and then raise a ticket. Make sure that you are logged with the merchant account.

**Comment by vipinsaini0** [comment]
My app is also crash, when I click on back button on "waiting for payment" screen.
see this screenshot- https://prnt.sc/ui4a56
and this below is error code:-
------------------------------
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <UIViewController: 0x7feb056718e0>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512a19b2 objc_exception_throw + 48
	2   UIKitCore                           0x00007fff48cd93fa -[UIViewController _presentViewController:withAnimationController:completion:] + 5218
	3   UIKitCore                           0x00007fff48cdb8ba __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	4   UIKitCore                           0x00007fff48cdbdc3 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	5   UIKitCore                           0x00007fff48cdb818 -[UIViewController _presentViewController:animated:completion:] + 187
	6   UIKitCore                           0x00007fff48cdba84 -[UIViewController presentViewController:animated:completion:] + 155
	7   PayUMoneyCoreSDK                    0x000000010acc8ae7 -[PUMAlertController showAnimated:] + 433
	8   PayUCustomBrowser                   0x000000010ad9a59f __38-[PUCBWebVC shouldRemoveVCOnBackPress]_block_invoke + 52
	9   libdispatch.dylib                   0x000000010aed8f11 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000010aed9e8e _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010aee7d97 _dispatch_main_queue_callback_4CF + 1149
	12  CoreFoundation                      0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x00007fff23d9c3b9 __CFRunLoopRun + 2041
	14  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	15  GraphicsServices                    0x00007fff38c05bbe GSEventRunModal + 139
	16  UIKitCore                           0x00007fff49372964 UIApplicationMain + 1605
	17  LootMantra                          0x000000010aa4c36b main + 75
	18  libdyld.dylib                       0x00007fff5211c1fd start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
------------------------------

**Comment by naveen488** [comment]
Hi @vipinsaini0,

have you found any solution for this issue?
because of am also getting the same crash in my app, can you help me with this?
