### ISSUE TITLE
Hash mismatch error

### ISSUE THREAD

**Issue by hemanth2k13** [payu-intrepos/PayUMoney-IOS-SDK#6]
Hi I'm using test key, salt found in sample app and setting type to test and using 
{
let hashSequence : NSString = "\(params.key!)|\(params.txnid!)|\(params.amount!)|\(params.productinfo!)|\(params.firstname!)|\(params.email!)|||||||||||\(self.salt)" as NSString
let data :NSString = utils.createSHA512(hashSequence as String!) as NSString
params.hashValue = data as String!
startPaymentFlow()
}
to generate hash. But i get hash mismatch error.

the hashSequence is printed like this

40747T|CFS2771911|14373.85|CFSProduct|hemanth|hemanth@gmail.com|||||||||||eCwWELxi

Am i doing anything wrong?

**Comment by iOSamit** [comment]
@hemanth2k13  you got solution?

**Comment by NitheeshU** [comment]
am too getting this error pls reply

**Comment by DishaMukherjee** [comment]
Hi All,

Kindly integrate with below link: https://github.com/payu-intrepos/PayUMoney-IOS-SDK/tree/master/PlugNPlay/Objective-C%20SampleApp

The hash sequence should be
hashSequence = key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5||||||salt.
$hash = hash("sha512", $hashSequence);

**Comment by ishteyaque06** [comment]
I am getting same issue, even I am using server **hash response**.  The server **hash response** is working fine with Android, but not in ios.

**Comment by shadabkhan1988** [comment]
Hi,

Kindly drop your queries on mobile.integration@payu.in

Also share the below details

1)PayU SDK version
2) Hash string
3) Error screenshot
4) Merchant key
