### ISSUE TITLE
Swift 5 and ios 13.6 getting Error.

### ISSUE THREAD

**Issue by kondak3** [payu-intrepos/PayUMoney-IOS-SDK#60]
`After open the bank page. back button taped its getting.`

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <UIViewController: 0x7fe473a91c90>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e55ce6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010da459b2 objc_exception_throw + 48
	2   UIKitCore                           0x000000011530843a -[UIViewController _presentViewController:withAnimationController:completion:] + 5218
	3   UIKitCore                           0x000000011530a8fa __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	4   UIKitCore                           0x000000011530ae03 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	5   UIKitCore                           0x000000011530a858 -[UIViewController _presentViewController:animated:completion:] + 187
	6   UIKitCore                           0x000000011530aac4 -[UIViewController presentViewController:animated:completion:] + 155
	7   PayUMoneyCoreSDK                    0x000000010dc93ae7 -[PUMAlertController showAnimated:] + 433
	8   PayUCustomBrowser                   0x000000010dd6559f __38-[PUCBWebVC shouldRemoveVCOnBackPress]_block_invoke + 52
	9   libdispatch.dylib                   0x00000001123b0f11 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001123b1e8e _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001123bfd97 _dispatch_main_queue_callback_4CF + 1149
	12  CoreFoundation                      0x000000010e4c0869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x000000010e4bb3b9 __CFRunLoopRun + 2041
	14  CoreFoundation                      0x000000010e4ba8a4 CFRunLoopRunSpecific + 404
	15  GraphicsServices                    0x0000000119de5bbe GSEventRunModal + 139
	16  UIKitCore                           0x00000001159a1968 UIApplicationMain + 1605
	17  PayUGateWay                         0x000000010d7cb05b main + 75
	18  libdyld.dylib                       0x000000011243d1fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by RajvinderPayU** [comment]
Can you help us with below-mentioned questions:

1. Is this happening only on iOS 13.6?
2. Is it happening in our Sample App as well?
3. which version of our SDK are you using?

**Comment by kondak3** [comment]
Hi,

Is this happening only on iOS 13.6?
`- application target is 13.0`
Is it happening in our Sample App as well?
`No. But its objective-c sample. We want swift. we created bridge header to access`
Which version of our SDK are you using?
`Sample containing SDK`

**Comment by RajvinderPayU** [comment]
Seems like an integration issue. Can you confirm the version number of our SDK? Also crash is happening on all the versions starting from iOS 13.0?

**Comment by kondak3** [comment]
We copied sdks from this project only. 
I think version 2.5.2

**Comment by RajvinderPayU** [comment]
Just checked on iOS 13.5 (will try on iOS 13.6 as well), it did not crash for me on a swift sample app. Can you share a sample code where it is crashing?

**Comment by kondak3** [comment]
can you please provide swift sample what you have.

**Comment by RajvinderPayU** [comment]
I just created a new project in swift and added our SDK via Cocoapods. It's a basic project not as customizable as our Objective-C's sample App, If you still need it, I can provide it.

**Comment by kondak3** [comment]
can you please  send pod formate payu sdk document. we will check this way.

**Comment by kondak3** [comment]
> I just created a new project in swift and added our SDK via Cocoapods. It's a basic project not as customizable as our Objective-C's sample App, If you still need it, I can provide it.

please provide.

**Comment by RajvinderPayU** [comment]
https://developer.payumoney.com/ios/

> can you please send pod formate payu sdk document. we will check this way.

**Comment by kondak3** [comment]
Hi Rajvinder,

Using Pod also getting same error. How can I share my sample project.

**Comment by RajvinderPayU** [comment]
> > I just created a new project in swift and added our SDK via Cocoapods. It's a basic project not as customizable as our Objective-C's sample App, If you still need it, I can provide it.
> 
> please provide.

https://we.tl/t-xkZOqVJBXT

**Comment by RajvinderPayU** [comment]
> Hi Rajvinder,
> 
> Using Pod also getting same error. How can I share my sample project.

You can share the zip file link here.

**Comment by RajvinderPayU** [comment]
For further assistance, please reach out to us at mobile.integration@payu.in

**Comment by kondak3** [comment]
please check this link
https://we.tl/t-uH5OMrgIYh

**Comment by RajvinderPayU** [comment]
@kondak3 We don't support apps with SceneDelegate, anyways, you want to support iOS 12 & above and SceneDelegate is supported only on iOS 13 and above. You will need to remove SceneDelegate from your app, our SDK will work after that.
