### ISSUE TITLE
404 Error getting after bank/card details enter and click pay button.

### ISSUE THREAD

**Issue by kondak3** [payu-intrepos/PayUMoney-IOS-SDK#61]
Hi,
we are getting 404 Error after bank/card details enter and click pay. 
before showing success transaction message.

But we are doing success transaction client to merchant and receiving  success response.
Every thing working fine.

**Comment by DishaMukherjee** [comment]
Hey Kondak

Kindly share the screen recording and error logs at help.payu.in
