### ISSUE TITLE
Code signing "PayUCustomBrowser.framework" failed.

### ISSUE THREAD

**Issue by surani444** [payu-intrepos/PayUMoney-IOS-SDK#63]
I'm getting this error from the App store while uploading the build. Can you help me out with this issue?
Xcode version: 12.3
Custom browser version: 5.9
![Screenshot 2021-01-19 at 6 12 15 PM](https://user-images.githubusercontent.com/32383405/105035997-df62b080-5a81-11eb-938c-54d871392b94.png)

**Comment by RajvinderPayU** [comment]
Have you done [this](https://github.com/payu-intrepos/PayUMoney-IOS-SDK/wiki/Releasing-to-Apple) in your project?

**Comment by surani444** [comment]
Yes,
![Screenshot 2021-01-19 at 6 33 28 PM](https://user-images.githubusercontent.com/32383405/105038095-e6d78900-5a84-11eb-965a-6e51ad80ac51.png)

**Comment by surani444** [comment]
Hi @RajvinderPayU 
Can you help me out with this issue?
Thanks

**Comment by RajvinderPayU** [comment]
Hi @surani444, this issue comes because of not adding that script, can you share a sample project where you can reproduce this error?

**Comment by RajvinderPayU** [comment]
Also, can you move that run script at the last and then try?

**Comment by surani444** [comment]
It will a bit difficult to create to sample project right now, but let me try as you mentioned in the last comment.
Thanks

**Comment by surani444** [comment]
> Also, can you move that run script at the last and then try?

This solution is worked. But may I know the reason why it's not working if I add this script to the 3rd position?
Thanks @RajvinderPayU

**Comment by RajvinderPayU** [comment]
As the libraries are attached after the script runs, the fat library is added to the archive and the main purpose of that script was to trim the fat binaries.

**Comment by surani444** [comment]
Thank you so much @RajvinderPayU
