### ISSUE TITLE
Swift 3, Not redirecting back to our app post payment success/failure.

### ISSUE THREAD

**Issue by vishalpawale** [payu-intrepos/PayUMoney-IOS-SDK#7]
Hello,

I'm developing iOS app using Swift 3. Everything goes well except after making payment transaction is not getting redirected back to our application. It just gets stuck on blank page. I'm using following success and failure urls:

> requestParams.surl = "https://www.payumoney.com/mobileapp/payumoney/success.php"
> requestParams.furl = "https://www.payumoney.com/mobileapp/payumoney/failure.php"

Please revert back, I'm not getting response from your support team. I'm trying to sync with them since last 3 days. We are not able go live only because of this issue.

**Comment by vipin04** [comment]
Hi Vishal,

Can you share the signature of callbacks you have written in Swift 3?

**Comment by vishalpawale** [comment]
Hello Vipin,

Turns out that you have put wrong callback signature in the sample swift apps:

The right ones are:

```
func transactinCanceledByUser() -> Void
func transactionCompleted(withResponse response : NSDictionary,errorDescription error:NSError) -> Void
func transactinFailed(withResponse response : NSDictionary,errorDescription error:NSError) -> Void
func transactinExpired(withResponse msg: NSString) -> Void
```
