### ISSUE TITLE
Do we need to set ITSAppUsesNonExemptEncryption to false?

### ISSUE THREAD

**Issue by nikhildange** [payu-intrepos/PayUMoney-IOS-SDK#8]
My application does not have as such any encryption  / cryptographic function implemented in it. However, we have integrated payUmoney in our app and you _might_ be using any cryptographic functions in the payUmoney framework. So should we be setting <<ITSAppUsesNonExemptEncryption>> to NO or YES ??

**Comment by Snehalr28** [comment]
Please share the answer if anybody knows as i am also having the same doubt??

**Comment by DishaMukherjee** [comment]
Kindly set value to NO for the same.
